tasks:
  - init: >
      echo "Setting up the environment...";
      pip install atopile;
      ato --version
    command: >
      echo "Ready to use atopile with the Voltage Divider example!";
      gp open atopile/readme_examples/voltage_divider.ato

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - https://open-vsx.org/api/atopile/atopile/0.2.15/file/atopile.atopile-0.2.15.vsix

