tasks:
  - init: >
      echo "Setting up the environment...";
      pip install atopile;
      ato --version;
      ato --help
    command: >
      echo "Ready to use atopile!";
      gp open docs\getting-started.md

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - https://open-vsx.org/api/atopile/atopile/0.2.15/file/atopile.atopile-0.2.15.vsix