tasks:
  - init: >
      echo "Setting up the environment..."
      source venv/bin/activate
      ato --version
    command: >
      echo "Ready to use AtoPile with the Voltage Divider example!"
      code readme_examples/voltage_divider.ato # This command opens the example file in VSCode

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - atopile/atopile@latest

