tasks:
  - init: >
      echo "Setting up the environment..."
      python -m venv venv
      source venv/bin/activate
      pip install atopile
      atopile --version
    command: >
      echo "Ready to use AtoPile with the Voltage Divider example!"
      code /workspace/atopile/readme_examples/voltage_divider.ato # This command opens the example file in VSCode

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - https://open-vsx.org/api/atopile/atopile/0.2.15/file/atopile.atopile-0.2.15.vsix

